services:
  calencare-web:
    build:
      context: ./
    ports:
      - "808:808"
      - "844:844"
    volumes:
      - ./frontend:/home/ubuntu/frontend
    environment:
      - NODE_ENV=production
    restart: unless-stopped